#server:
#  port: 8888
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: C:\Users\pvdat\Desktop\congif-repo
#          search-paths: demo
#  application:
#    name: Config-server
##          username: phamvandat207
##          password: Chetdoingay15

#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations:
#            - file:///C:/Users/pvdat/Downloads/springboot-eureka/springboot-eureka/config-server/src/main/resources/
